project 'Wkwebview.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Wkwebview' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Wkwebview
  pod 'SDWebImage', '~> 4.0.0-beta2'

  target 'WkwebviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WkwebviewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
